database_path = "./vector_database/chroma_langchain_db"
documents_directory = "docs/import"
collection_name = "youtube_videos"
chunk_size = 1024
chunk_overlap = 105
batch_size = 10
show_logs = True
discord_channel = "github"
embedding_model = "qwen3-embedding:8b"
use_remote_llm = True
remote_llm = "qwen3:32b"
local_llm = "qwen3:8b"
video_ids_separator = "__"
bot_greeting = "Hello. This is Garys Economics Youtube chatbot. You can ask me questions and I'll answer them using the content of our videos."
