services:
  telegram-bot:
    image: ghcr.io/garyseconomics/chatbot:latest
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./content_database/data:/app/content_database/data
    command: ["python", "-m", "interfaces.telegram_bot"]
    tty: true

  discord-bot:
    image: ghcr.io/garyseconomics/chatbot:latest
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./content_database/data:/app/content_database/data
    command: ["python", "-m", "interfaces.discord_bot"]
    tty: true