services:
  telegram-bot:
    image: ghcr.io/garyseconomics/chatbot:latest
    build: .
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./docs/import:/app/docs/import
      - ./vector_database:/app/vector_database
    command: ["python", "telegram_bot.py"]
    tty: true

#  discord-bot:
#    image: ghcr.io/garyseconomics/chatbot:latest
#    build: .
#    env_file:
#      - .env
#    restart: unless-stopped
#    volumes:
#      - ./docs/import:/app/docs/import
#      - ./vector_database:/app/vector_database
#    command: ["python", "discord_bot.py"]
#    tty: true